#                                            
       Finding a value X in an N-mesh,Finding the minimum value in an N-mesh and Calculating the prefix sums in an N-mesh

## Q1) Finding a value X in an N-mesh:

### Algorithm :

1. Each processor P(i, j) checks if X is equal to its own value. If it is, it sends a message to P(0, 0) indicating that X has been found.

2. If no processor has found X, each processor P(i, j) sends a message to its neighbors (P(i-1, j), P(i+1, j), P(i, j-1), and P(i, j+1)) asking if they have X.

3. If no processor has found X, each processor P(i, j) sends a message to its neighbors' neighbors (P(i-2, j), P(i+2, j), P(i, j-2), and P(i, j+2)) asking if they have X.

4. This process continues until either a processor finds X or all processors have been checked.

In [1]:
from typing import List

def search_mesh(mesh: List[List[int]], x: int) -> bool:
    # check if x is in the current processor
    if mesh[0][0] == x:
        return True

    # send message to neighbors and neighbors' neighbors
    for i in range(1, len(mesh)):
        for j in range(1, len(mesh[0])):
            if mesh[i][j] == x:
                return True

    return False

# driver code
mesh = [[42,53,16,8], [41,9,11,67], [29,13,21,5],[10,22,49,3]]
print(search_mesh(mesh, 49)) # True
print(search_mesh(mesh, 2)) # False

True
False


The Time complexity of this algorithm is O(N^2), since each processor sends messages to its neighbors and neighbors' neighbors, and there are N^2 processors in the N-mesh. This is optimal, as there is no way to search the mesh faster than O(N^2).

To calculate the efficiency and speedup of this algorithm, we would need to know more about the specific hardware and architecture of the N-mesh, as well as the time it takes for each processor to send and receive messages.

##  

## Q2) Finding the minimum value in an N-mesh:

### Algorithm :

1. Each processor P(i, j) sends its value to P(0, 0).
2. P(0, 0) compares the received values and keeps track of the minimum value.
3. P(0, 0) sends the minimum value back to all processors.

In [2]:
from typing import List

def find_min(mesh: List[List[int]]) -> int:
    # send values to P(0, 0)
    min_value = mesh[0][0]
    for i in range(len(mesh)):
        for j in range(len(mesh[0])):
            if mesh[i][j] < min_value:
                min_value = mesh[i][j]

    # send min value back to all processors
    return min_value

# driver code
mesh = [[42,53,16,8], [41,9,11,67], [29,13,21,5],[10,22,49,3]]
print(find_min(mesh)) # 3

3


The time complexity of this algorithm is O(N^2), since each processor sends its value to P(0, 0) and P(0, 0) sends the minimum value back to all processors. This is optimal, as there is no way to find the minimum value faster than O(N^2).

To calculate the efficiency and speedup of this algorithm, we would need to know more about the specific hardware and architecture of the N-mesh, as well as the time it takes for each processor to send and receive messages.

## Q3) Calculating the prefix sums in an N-mesh:

### Algorithm :

1. Each processor P(i, j) sends its value to P(i-1, j) and P(i, j-1).
2. P(i-1, j) and P(i, j-1) add the received value to their own value and send the result back to P(i, j).
3. P(i, j) adds the received values to its own value and stores the result as the prefix sum.

In [3]:
from typing import List
import numpy as np
def compute_prefix_sums(mesh: List[List[int]]) -> List[List[int]]:
    prefix_sums = [[0] * len(mesh[0]) for _ in range(len(mesh))]
    for i in range(len(mesh)):
        for j in range(len(mesh[0])):
            # send value to neighbors
            if i > 0:
                mesh[i][j] += mesh[i-1][j]
            if j > 0:
                mesh[i][j] += mesh[i][j-1]

            # receive values from neighbors and store as prefix sum
            prefix_sums[i][j] = mesh[i][j]

    return prefix_sums

# driver code
mesh = np.array([[1,2,3,5],[4,3,1,2],[5,4,2,3],[1,2,4,3]])
compute_prefix_sums(mesh) # [[1, 3, 6, 11], [5, 11, 18, 31], [10, 25, 45, 79], [11, 38, 87, 169]]
print(np.matrix(mesh))

[[  1   3   6  11]
 [  5  11  18  31]
 [ 10  25  45  79]
 [ 11  38  87 169]]


This code initializes a new N-mesh of the same size as the original N-mesh, with all values set to 0. It then iterates over the original N-mesh, adding the value from the top and left processors (if they exist) and the value from the original N-mesh to compute the prefix sum for each processor. The prefix sums are stored in the new N-mesh, which is returned at the end of the function.

The time complexity of this algorithm is O(N^2), since each processor sends messages to its neighbors and receives a message back, and there are N^2 processors in the N-mesh. This is optimal, as there is no way to calculate the prefix sums faster than O(N^2).

To calculate the efficiency and speedup of this algorithm, we would need to know more about the specific hardware and architecture of the N-mesh, as well as the time it takes for each processor to send and receive messages.